version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "flask*"
          - "google*"
          - "python*"
          - "colorama"
          - "grpcio"
          - "gunicorn"
          - "pika"
          - "pyyaml"
          - "requests"
          - "sdc-cryptography"
          - "structlog"
          - "ua-parser"
          - "blinker"
          - "boto3"
          - "humanize"
          - "marshmallow"
          - "jsonpointer"
          - "redis"
          - "htmlmin"
          - "coloredlogs"
          - "uwsgi"
          - "email-validator"
          - "itsdangerous"
          - "simplejson"
          - "markupsafe"
          - "pdfkit"
          - "ordered-set"
          - "cachetools"
          - "gevent"
          - "babel"
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "pytest*"
          - "flake8*"
          - "pylint*"
          - "types*"
          - "pep8"
          - "mock"
          - "jsonschema"
          - "beautifulsoup4"
          - "httmock"
          - "moto"
          - "freezegun"
          - "fakeredis"
          - "mypy"
          - "responses"
          - "playwright"
          - "black"
          - "djlint"
    ignore:
      - dependency-name: "pylint*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "babel"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "pytest*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "flake8*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "types*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pep8"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "mock"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "jsonschema"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "beautifulsoup4"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "httmock"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "moto"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "freezegun"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "fakeredis"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "mypy"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "responses"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "playwright"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "black"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "djlint"
        update-types: ["version-update:semver-minor"]
