version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "08:00"
      timezone: "Europe/London"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "08:00"
      timezone: "Europe/London"
    versioning-strategy: increase-if-necessary
    labels:
      - "dependencies"
      - "node"
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@wdio*"
          - "@babel*"
          - "eslint*"
          - "json*"
          - "jsrsasign*"
          - "lint-staged*"
          - "livereload*"
          - "node-forge*"
          - "prettier*"
          - "typescript*"
          - "uuid*"
          - "webdriverio*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
      timezone: "Europe/London"
    # Workaround to have two "pip" ecosystems: actively setting "target-branch: main" for one config, and leaving it unset for the other config
    target-branch: main
    versioning-strategy: increase-if-necessary
    labels:
      - "dependencies"
      - "python"
    allow:
      - dependency-type: "production"
    groups:
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "flask*"
          - "google*"
          - "python*"
          - "colorama"
          - "grpcio"
          - "gunicorn"
          - "pika"
          - "pyyaml"
          - "requests"
          - "sdc-cryptography"
          - "structlog"
          - "ua-parser"
          - "blinker"
          - "boto3"
          - "humanize"
          - "marshmallow"
          - "jsonpointer"
          - "redis"
          - "htmlmin"
          - "coloredlogs"
          - "uwsgi"
          - "email-validator"
          - "itsdangerous"
          - "simplejson"
          - "markupsafe"
          - "pdfkit"
          - "ordered-set"
          - "cachetools"
          - "gevent"
          - "babel"
    ignore:
      # "babel" temporarily pinned to v2.14.0 - problem for translations found in v2.15.0, see: https://github.com/ONSdigital/eq-questionnaire-runner/pull/1384
      - dependency-name: "babel"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "08:00"
      timezone: "Europe/London"
    versioning-strategy: increase-if-necessary
    labels:
      - "dependencies"
      - "python-dev"
    allow:
      - dependency-type: "development"
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "pytest*"
          - "flake8*"
          - "pylint*"
          - "types*"
          - "pep8"
          - "mock"
          - "jsonschema"
          - "beautifulsoup4"
          - "httmock"
          - "moto"
          - "freezegun"
          - "fakeredis"
          - "mypy"
          - "responses"
          - "playwright"
          - "black"
          - "djlint"
