changelog:
  categories:
    - title: ⚠️ Breaking Changes
      labels:
        - Breaking Changes
    - title: New Features
      labels:
        - New Features
    - title: Enhancements
      labels:
        - Enhancement
    - title: Bug Fixes
      labels:
        - Bug Fix
    - title: Documentation
      labels:
        - Documentation
    - title: Other Changes
      labels:
        - "*"
