version: "3"

services:
    datastore:
        image: knarz/datastore-emulator
        networks:
            - eq-env
        ports:
            - "8432:8432"

    redis:
        image: redis:4
        networks:
            - eq-env
        ports:
            - "6379:6379"

    eq-questionnaire-launcher:
        image: onsdigital/eq-questionnaire-launcher:latest
        environment:
            SURVEY_RUNNER_URL: http://localhost:5000
            SURVEY_RUNNER_SCHEMA_URL: http://host.docker.internal:5000
        networks:
            - eq-env
        restart: always
        ports:
            - "8000:8000"

networks:
    eq-env:
        driver: bridge
