services:
    datastore:
        image: knarz/datastore-emulator
        networks:
            - eq-env
        ports:
            - "8432:8432"

    redis:
        image: redis:8.2.2
        networks:
            - eq-env
        ports:
            - "6379:6379"

    eq-questionnaire-launcher:
        image: europe-west2-docker.pkg.dev/ons-eq-ci/docker-images/eq-questionnaire-launcher:latest
        environment:
            SURVEY_RUNNER_URL: http://localhost:5000
            SURVEY_RUNNER_SCHEMA_URL: http://host.docker.internal:5000
            SDS_API_BASE_URL: http://host.docker.internal:5003
            CIR_API_BASE_URL: http://host.docker.internal:5004
        networks:
            - eq-env
        restart: always
        ports:
            - "8000:8000"

    sds:
        image: europe-west2-docker.pkg.dev/ons-eq-ci/docker-images/sds:latest
        networks:
            - eq-env
        restart: always
        ports:
            - "5003:5003"

    cir:
        image: europe-west2-docker.pkg.dev/ons-eq-ci/docker-images/cir:latest
        networks:
            - eq-env
        restart: always
        ports:
            - "5004:5004"

networks:
    eq-env:
        driver: bridge
