---
version: '3'

services:
  ajv-validator:
    image: onsdigital/eq-questionnaire-validator:${calculated-summary-min-max}-ajv
    networks:
      - eq-schema
    ports:
      - 5002:5002

  py-validator:
    image: onsdigital/eq-questionnaire-validator:${calculated-summary-min-max}
    networks:
      - eq-schema
    environment:
      AJV_HOST: ajv-validator
    ports:
      - 5001:5000
    depends_on:
      - ajv-validator
networks:
  eq-schema:
    driver: bridge
