name: eq-runner
channels:
  - conda-forge
dependencies:
  - python=3.14.6
  - nodejs=22.13.0   # closest available patch to .nvmrc's v22.15.0
  - poetry=2.4.2
  - snappy
  - jq
  - pip
variables:
  POETRY_VIRTUALENVS_CREATE: "false"
