import MandatoryCheckboxPage from "../generated_pages/dynamic_answers_checkbox/mandatory-checkbox.page";
import DynamicAnswerPage from "../generated_pages/dynamic_answers_checkbox/dynamic-answer.page";
import SubmitPage from "../generated_pages/dynamic_answers_checkbox/submit.page";

describe("Dynamic answers checkbox answer value source", () => {
  const optionTesco = 'input[id="percentage-of-shopping-tesco"]';
  const optionAldi = 'input[id="percentage-of-shopping-aldi"]';
  const optionAsda = 'input[id="percentage-of-shopping-asda"]';
  const optionSainsburys = 'input[id="percentage-of-shopping-sainsburys"]';
  const summaryTesco = 'dl[id="percentage-of-shopping-tesco"]';
  const summaryAldi = 'dl[id="percentage-of-shopping-aldi"]';
  const summaryAsda = 'dl[id="percentage-of-shopping-asda"]';
  const summarySainsburys = 'dl[id="percentage-of-shopping-sainsburys"]';
  const summaryAsdaEdit = 'a[data-qa="percentage-of-shopping-asda-edit"]';
  const summaryAldiEdit = 'a[data-qa="percentage-of-shopping-aldi-edit"]';
  beforeEach("Load the survey", async () => {
    await browser.openQuestionnaire("test_dynamic_answers_checkbox.json");
  });

  it("Given checkbox options have been picked for a checkbox answer, When the dynamic answers are displayed, Then the correct answers should be visible", async () => {
    await $(MandatoryCheckboxPage.asda()).click();
    await $(MandatoryCheckboxPage.tesco()).click();
    await $(MandatoryCheckboxPage.submit()).click();
    await expect(await $(optionTesco).isDisplayed()).to.be.true;
    await expect(await $(optionAldi).isDisplayed()).to.be.false;
    await expect(await $(optionAsda).isDisplayed()).to.be.true;
    await expect(await $(optionSainsburys).isDisplayed()).to.be.false;
  });
  it("Given checkbox options have been picked for a checkbox answer, When other options for the checkbox answer are picked, Then the correct dynamic answers are displayed", async () => {
    await $(MandatoryCheckboxPage.asda()).click();
    await $(MandatoryCheckboxPage.tesco()).click();
    await $(MandatoryCheckboxPage.submit()).click();
    await $(DynamicAnswerPage.previous()).click();
    await $(MandatoryCheckboxPage.tesco()).click();
    await $(MandatoryCheckboxPage.submit()).click();
    await expect(await $(optionTesco).isDisplayed()).to.be.false;
    await expect(await $(optionAldi).isDisplayed()).to.be.false;
    await expect(await $(optionAsda).isDisplayed()).to.be.true;
    await expect(await $(optionSainsburys).isDisplayed()).to.be.false;
  });
  it("Given checkbox options have been picked for a checkbox answer and the dynamic answers are submitted, When the summary is displayed, Then the correct answers should be visible and have correct values", async () => {
    await $(MandatoryCheckboxPage.asda()).click();
    await $(MandatoryCheckboxPage.tesco()).click();
    await $(MandatoryCheckboxPage.submit()).click();
    await $(optionTesco).setValue(5);
    await $(optionAsda).setValue(15);
    await $(DynamicAnswerPage.submit()).click();
    await expect(await $(summaryTesco).isDisplayed()).to.be.true;
    await expect(await $(summaryTesco).getText()).to.contain("5");
    await expect(await $(summaryAldi).isDisplayed()).to.be.false;
    await expect(await $(summaryAsda).isDisplayed()).to.be.true;
    await expect(await $(summaryAsda).getText()).to.contain("15");
    await expect(await $(summarySainsburys).isDisplayed()).to.be.false;
  });
  it("Given checkbox options have been picked for a checkbox answer and the dynamic answers are submitted, When the dynamic answers are revisited, Then they should be visible and have correct values", async () => {
    await $(MandatoryCheckboxPage.sainsburyS()).click();
    await $(MandatoryCheckboxPage.tesco()).click();
    await $(MandatoryCheckboxPage.submit()).click();
    await $(optionTesco).setValue(5);
    await $(optionSainsburys).setValue(15);
    await $(DynamicAnswerPage.submit()).click();
    await $(SubmitPage.previous()).click();
    await expect(await $(optionTesco).isDisplayed()).to.be.true;
    await expect(await $(optionTesco).getAttribute("value")).to.equal("5");
    await expect(await $(optionSainsburys).isDisplayed()).to.be.true;
    await expect(await $(optionSainsburys).getAttribute("value")).to.equal("15");
  });
  it("Given checkbox options have been picked for a checkbox answer and the dynamic answers are submitted, When the dynamic answers are resubmitted with options unpicked, Then they should be displayed correctly on summary", async () => {
    await $(MandatoryCheckboxPage.asda()).click();
    await $(MandatoryCheckboxPage.tesco()).click();
    await $(MandatoryCheckboxPage.submit()).click();
    await $(optionTesco).setValue(5);
    await $(optionAsda).setValue(15);
    await $(DynamicAnswerPage.submit()).click();
    await $(SubmitPage.mandatoryCheckboxAnswerEdit()).click();
    await $(MandatoryCheckboxPage.tesco()).click();
    await $(MandatoryCheckboxPage.submit()).click();
    await $(DynamicAnswerPage.submit()).click();
    await expect(await $(summaryTesco).isDisplayed()).to.be.false;
    await expect(await $(summaryAldi).isDisplayed()).to.be.false;
    await expect(await $(summaryAsda).isDisplayed()).to.be.true;
    await expect(await $(summaryAsda).$("dd").getText()).to.equal("15%");
    await expect(await $(summarySainsburys).isDisplayed()).to.be.false;
  });
  it("Given checkbox options have been picked for a checkbox answer and the dynamic answers are submitted, When the summary edit answer link is used for dynamic answer, Then the focus is on correct answer option and the correct values are displayed", async () => {
    await $(MandatoryCheckboxPage.asda()).click();
    await $(MandatoryCheckboxPage.aldi()).click();
    await $(MandatoryCheckboxPage.submit()).click();
    await $(optionAldi).setValue(5);
    await $(optionAsda).setValue(15);
    await $(DynamicAnswerPage.submit()).click();
    await $(summaryAsdaEdit).click();
    await expect(await $(optionAsda).isFocused()).to.be.true;
    await expect(await $(optionAsda).getAttribute("value")).to.equal("15");
    await expect(await $(optionAldi).isFocused()).to.be.false;
    await expect(await $(optionAldi).getAttribute("value")).to.equal("5");
    await $(DynamicAnswerPage.submit()).click();
    await $(summaryAldiEdit).click();
    await expect(await $(optionAldi).isFocused()).to.be.true;
    await expect(await $(optionAldi).getAttribute("value")).to.equal("5");
    await expect(await $(optionAsda).isFocused()).to.be.false;
    await expect(await $(optionAsda).getAttribute("value")).to.equal("15");
  });
  it("Given checkbox options have been picked for a checkbox answer and the dynamic answers are submitted, When the dynamic answers are resubmitted with new options picked, Then they should be displayed correctly on summary", async () => {
    await $(MandatoryCheckboxPage.asda()).click();
    await $(MandatoryCheckboxPage.tesco()).click();
    await $(MandatoryCheckboxPage.submit()).click();
    await $(optionTesco).setValue(5);
    await $(optionAsda).setValue(15);
    await $(DynamicAnswerPage.submit()).click();
    await $(SubmitPage.mandatoryCheckboxAnswerEdit()).click();
    await $(MandatoryCheckboxPage.aldi()).click();
    await $(MandatoryCheckboxPage.submit()).click();
    await $(optionAldi).setValue(25);
    await $(DynamicAnswerPage.submit()).click();
    await expect(await $(summaryTesco).isDisplayed()).to.be.true;
    await expect(await $(summaryTesco).$("dd").getText()).to.equal("5%");
    await expect(await $(summaryAldi).isDisplayed()).to.be.true;
    await expect(await $(summaryAldi).$("dd").getText()).to.equal("25%");
    await expect(await $(summaryAsda).isDisplayed()).to.be.true;
    await expect(await $(summaryAsda).$("dd").getText()).to.equal("15%");
    await expect(await $(summarySainsburys).isDisplayed()).to.be.false;
  });
  it("Given checkbox options have been picked for a checkbox answer and the dynamic answers are submitted, When the dynamic answers are resubmitted with new options picked and old options unpicked, Then they should be displayed correctly on summary", async () => {
    await $(MandatoryCheckboxPage.asda()).click();
    await $(MandatoryCheckboxPage.tesco()).click();
    await $(MandatoryCheckboxPage.submit()).click();
    await $(optionTesco).setValue(5);
    await $(optionAsda).setValue(15);
    await $(DynamicAnswerPage.submit()).click();
    await $(SubmitPage.mandatoryCheckboxAnswerEdit()).click();
    await $(MandatoryCheckboxPage.aldi()).click();
    await $(MandatoryCheckboxPage.asda()).click();
    await $(MandatoryCheckboxPage.tesco()).click();
    await $(MandatoryCheckboxPage.submit()).click();
    await $(optionAldi).setValue(25);
    await $(DynamicAnswerPage.submit()).click();
    await expect(await $(summaryTesco).isDisplayed()).to.be.false;
    await expect(await $(summaryAldi).isDisplayed()).to.be.true;
    await expect(await $(summaryAldi).$("dd").getText()).to.equal("25%");
    await expect(await $(summaryAsda).isDisplayed()).to.be.false;
    await expect(await $(summarySainsburys).isDisplayed()).to.be.false;
  });
});
