{{- if .Values.cloudArmor.policyName -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: "runner-backend-config"
spec:
  securityPolicy:
    name: {{ .Values.cloudArmor.policyName }}
{{- end }}
