{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
      kubernetes.io/ingress.global-static-ip-name: survey-runner
      ingress.gcp.kubernetes.io/pre-shared-cert: runner
      kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - http:
      paths:
      - path: /session/*
        backend:
          serviceName: runner
          servicePort: 80
      - path: /questionnaire/*
        backend:
          serviceName: runner
          servicePort: 80
      - path: /submitted/*
        backend:
          serviceName: runner
          servicePort: 80
      - path: /individual-response/*
        backend:
          serviceName: runner
          servicePort: 80
      - path: /status
        backend:
          serviceName: runner
          servicePort: 80
      - path: /schemas
        backend:
          serviceName: runner
          servicePort: 80
      - path: /flush
        backend:
          serviceName: runner
          servicePort: 80
{{- end }}
