name: Design System release PR

on:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  create-pull-request:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - run: |
          TAG=$(curl https://api.github.com/repos/ONSdigital/design-system/releases/latest -s | jq .name -r)
          echo "DESIGN_SYSTEM_VERSION=$TAG" >> $GITHUB_ENV
          echo "CURRENT_DESIGN_SYSTEM_VERSION=$(cat .design-system-version)" >> $GITHUB_ENV
      - if: ${{ env.CURRENT_DESIGN_SYSTEM_VERSION }} != ${{ env.DESIGN_SYSTEM_VERSION }}
        name: Update and commit design system version
        run: |
          # Import GPG key to sign the commit
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --import --no-tty --batch --yes

          # Set Git GPG program and signing key
          git config --global gpg.program $(which gpg)
          git config --global user.signingkey "${{ secrets.GPG_KEY_ID }}"

          # Update Git user details to match gpg key
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

          # Update and commit design system version file
          echo $DESIGN_SYSTEM_VERSION > .design-system-version
          git add -A
          git commit -S -m "Update design system version to $DESIGN_SYSTEM_VERSION"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: "${{ secrets.REPO_ACCESS_TOKEN }}"
          commit-message: "Update design system to version ${{ env.DESIGN_SYSTEM_VERSION }}"
          title: "Update design system to version ${{ env.DESIGN_SYSTEM_VERSION }}"
          body: |
            This is an auto-generated PR.
            Design system release: https://github.com/ONSdigital/design-system/releases/tag/${{ env.DESIGN_SYSTEM_VERSION }}
          branch: "design-system-release-${{ env.DESIGN_SYSTEM_VERSION }}"
