name: Main

on:
  push:
    branches:
      - tiles-schema-dev

jobs:
  docker-push:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3
        - name: Set Tag and SHA
          run: |
            echo "TAG=tiles-schema-dev" >> $GITHUB_ENV
        - name: Write app version
          run: printf "$GITHUB_SHA" > .application-version
        - name: Build
          run: >
            docker build -t onsdigital/eq-questionnaire-runner:$TAG
            -t ${{ secrets.GAR_LOCATION }}/${{ secrets.GAR_PROJECT_ID }}/docker-images/eq-questionnaire-runner:$TAG .
        - name: Push to GAR
          env:
            GAR_SERVICE_KEY: ${{ secrets.GAR_SERVICE_KEY }}
          run: |
            echo $GAR_SERVICE_KEY | docker login -u _json_key --password-stdin https://${{ secrets.GAR_LOCATION }}
            gcloud auth configure-docker ${{ secrets.GAR_LOCATION }}
            echo "Pushing to GAR with tag $TAG"
            docker push ${{ secrets.GAR_LOCATION }}/${{ secrets.GAR_PROJECT_ID }}/docker-images/eq-questionnaire-runner:$TAG
