name: Master

on:
  push:
    branches:
      - master

jobs:
  docker-push:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - name: Write app version
          run: printf "$GITHUB_SHA" > .application-version
        - name: Build
          run: >
            docker build -t onsdigital/eq-questionnaire-runner:latest .
        - name: Push to Docker Hub
          run: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            echo "Pushing with tag [latest]"
            docker push onsdigital/eq-questionnaire-runner:latest
