name: Merge

on:
  push:
    branches:
      - master

jobs:
  docker-push:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Write app version
          run: printf "${{ github.event.push.head }}" > .application-version
        - name: Build
          run: docker build -t onsdigital/eq-questionnaire-runner:latest .
        - name: Push
          run: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}}
            echo "Pushing with tag [$TAG]"
            docker push onsdigital/eq-questionnaire-runner:$TAG

