---
name: MegaLinter

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  GITHUB_STATUS_REPORTER: false
  GITHUB_COMMENT_REPORTER: false

concurrency:
  group: "${{ github.head_ref || github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@ef3e84b8b836d76db562d0f3ed7da61e8fd538bc # v9.6.0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
