name: mutmut

on:
  push:
    branches:
      - spike-mutation-testing-mutmut

jobs:

  python-dependencies:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pipenv'
      - name: Install Pipenv
        run: pip install pipenv==2023.8.22
      - name: Install virtual environment
        run: |
          sudo apt-get install libsnappy-dev
          pipenv install --dev

  test-mutmut:
    needs: [python-dependencies]
    strategy:
      matrix:
        mutation-module-under-test: [ questionnaire ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pipenv'
      - name: Install apt dependencies
        run: |
            sudo apt-get install libsnappy-dev libgconf-2-4 jq

            # Install wkthtmltopdf with patched Qt
            sudo apt-get install -y xfonts-base xfonts-75dpi
            wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
            sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
      - name: Write app version
        run: printf "local" > .application-version
      - name: Install pipenv
        run: pip install pipenv==2023.8.22
      - name: Install virtual environment
        run: pipenv install --dev
      - name: Load templates
        run: make load-design-system-templates
      - name: Compile translations
        run: make translate
      - name: Link env vars
        run: ln -sf .development.env .env
      - name: Docker compose for int testing
        run: docker-compose --version && RUNNER_ENV_FILE=.functional-tests.env docker-compose up --build -d
      - name: Run mutmut
        run: |
            pipenv run mutmut run \
                --paths-to-mutate "app/${{ matrix.module }}/" \
                --runner "py.test -n auto --cov=app" \
                --use-coverage \
                --no-progress \
                --CI
      - name: Save HTML output
        run: |
            pipenv run mutmut html
      - uses: actions/upload-artifact@v3
        with:
            name: mutation-test-report
            path: html/
      - name: Docker compose shutdown
        run: RUNNER_ENV_FILE=.functional-tests.env docker-compose kill
